<script src="/static-assets/bower_components/what-input/what-input.min.js" type="text/javascript"></script>
<script src="/static-assets/bower_components/foundation-sites/dist/foundation.min.js" type="text/javascript"></script>
<script src="/static-assets/js/jquery.showmore.src-min.js" type="text/javascript"></script>
<script src="/static-assets/js/app-min.js" type="text/javascript"></script>
<script src="/static-assets/layerslider/js/greensock.js" type="text/javascript"></script>
<script src="/static-assets/layerslider/js/layerslider.transitions.js" type="text/javascript"></script>
<script src="/static-assets/layerslider/js/layerslider.kreaturamedia.jquery.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.0/moment.min.js" type="text/javascript"></script>
<script src="/static-assets/js/inewsticker.js" type="text/javascript"></script>
<script src="/static-assets/js/jquery.kyco.easyshare-min.js" type="text/javascript"></script>
<script src="/static-assets/js/jquery.matchHeight-min.js" type="text/javascript"></script>
<script src="/static-assets/videojs/video.min.js" type="text/javascript"></script>
<script src="/static-assets/videojs/videojs-contrib-hls.min.js" type="text/javascript"></script>
<script src="/static-assets/js/hls.min.js" type="text/javascript"></script>
<script src="/static-assets/js/jquery.time-to.min.js" type="text/javascript"></script>
<script src="/static-assets/js/countdowntimer-min.js" type="text/javascript"></script>
